spring:
  servlet:
    multipart:
      max-file-size: 275661011
      max-request-size: 275661011
      location: D:/
  profiles:
    active: '@spring.profiles.active@'
  application:
    name: "application"
  codec:
    log-request-details: true #debug 开启request请求参数打印
  task:
    scheduling:
      pool:
        size: 8  #更改定时任务线程池的线程大小
  mvc:
    log-request-details: true #debug下打印请求参数
    servlet:
      load-on-startup: 1
    hiddenmethod:
      filter:
        enabled: true
  jackson:
    time-zone: GMT+8:00
    date-format:
  datasource:
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 120000
      maximum-pool-size: 20


server:
  servlet:
    encoding:
      force: true
      charset: UTF-8
  tomcat:
    max-connections: 10000
    threads:
      max: 10000
      min-spare: 100

  http2:
    enabled: true
  port: 8080
  compression:
    enabled: true
#mybatis:
#  mapper-locations: classpath:**/mapper/*.xml #xml文件位置
debug: off
mybatis:
  configuration:
    default-enum-type-handler:
---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306?useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    password: root
    username: 123456
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.1.3:3307?useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

