spring:
  profiles:
    active: '@spring.profiles.active@'
  application:
    name: "application"
  codec:
    log-request-details: true #debug 开启request请求参数打印
  task:
    scheduling:
      pool:
        size: 8  #更改定时任务线程池的线程大小
  mvc:
    log-request-details: true #debug下打印请求参数
    servlet:
      load-on-startup: 9999 #dispatcher new的优先级
  jackson:
    time-zone: GMT+8:00
  devtools:
    livereload:
      enabled: true
server:
  port: 80
  compression:
    enabled: off
mybatis:
  mapper-locations: classpath:**/mapper/*.xml,classpath:**/dao/*.xml
  configuration:
    default-enum-type-handler: demo.mybatis.typehandler.EnumTypeHandler
debug: off

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306/testDB?useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    password: admin
    username: root
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/test?useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    password: 123456
    username: root

