spring:
  application:
    name: "webapplcation"
  codec:
    log-request-details: true #开启request请求参数打印
  task:
    scheduling:
      pool:
        size: 8  #更改定时人的线程大小
  thymeleaf:
    cache: false

debug: true

