spring:
  datasource:
    url: jdbc:mysql://localhost:3307/security_test?useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    password: 123456
    username: root
    initialization-mode: always
    platform: mysql
    schemaUsername: ${spring.datasource.username}
    schemaPassword: ${spring.datasource.password}
    schema:
      - classpath:init/schema-${spring.datasource.platform}.sql
    data:
      - classpath:init/data-${spring.datasource.platform}.sql
    continue-on-error: true
  redis:
    timeout: 0
    database: 0
    #Redis服务器地址
    host: localhost
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-idle: 8
  cache:
    redis:
      time-to-live: 6h
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_null
  task:
    scheduling:
      pool:
        size: 8
  security:
    user:
      password: 123456
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: security.config.SqlPrint
  mapper-locations: classpath:**/mapper/**/*.xml
server:
  port: 8080
logging:
  level:
    security: debug