spring:
  datasource:
    url: jdbc:mysql://localhost:3307/test?useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    password: 123456
    username: root
  redis:
    timeout: 0
    database: 0
    #Redis服务器地址
    host: localhost
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-idle: 8
  cache:
    redis:
      time-to-live: 6h
  jackson:
    time-zone: GMT+8
  task:
    scheduling:
      pool:
        size: 8
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: security.config.SqlPrint

server:
  port: 8080
