###
GET http://localhost:8080/lucene/normalQuery?keyWord=price&value=9


### id
GET http://localhost:8080/lucene/normalQuery?keyWord=id&value=11111

###
POST http://localhost:8080/lucene/testAddByClass
Content-Type: application/json

{
  "id": 11111,
  "name": "中老年人保暖内衣开衫男士冬大码加绒加厚纯棉老人超柔黄金甲套装",
  "category": "内衣会场",
  "price": 250.0,
  "place": "浙江金华",
  "code": "539129852651"
}

