iteminfoconfig:
  items:
    1025:
      MicroscopyWorm_0007: HEL
      FecesMicroscopyWhite_0007: JJWBC
      FecesMicroscopyRed_0007: JJRBC
      FecesColor_0007: COL
      FecesCharacter_0007: CHA
    1023:
      FecesMicroscopyWhite_0007: WBC1
      FecesMicroscopyRed_0007: RBC1
      UricLeukocyteEsterase_0007: UWBC